### ISSUE TITLE
a little bug of test_demo.py 

### ISSUE THREAD

**Issue by GuangtaoLyu** [PantoMatrix/PantoMatrix#109]
The generated character shifts to the left and eventually disappears completely into the video in the latest codes.

![image](https://github.com/PantoMatrix/PantoMatrix/assets/57834464/e0543d2c-0b0b-433f-b962-8ddba72f8f2a)

![image](https://github.com/PantoMatrix/PantoMatrix/assets/57834464/d4e98efe-8717-4cca-abda-1c7314f5e072)

![image](https://github.com/PantoMatrix/PantoMatrix/assets/57834464/654b6fc1-cafc-48ff-b459-8e9318bb7c5d)

**Comment by wubowen416** [comment]
Hi, thank you for reporting this issue.

I think it is because the result has translation thus it is moving, but the camera is being fixed.
I will try to the fix the camera to look at the center of those vertices.

For a temporary workaround, you can try to set the translation to 0 in the following:

https://github.com/PantoMatrix/PantoMatrix/blob/2cbbce525cef7ca424473de8b08ee1556a99a014/scripts/EMAGE_2024/utils/other_tools.py#L652

https://github.com/PantoMatrix/PantoMatrix/blob/2cbbce525cef7ca424473de8b08ee1556a99a014/scripts/EMAGE_2024/utils/other_tools.py#L665

For example, change it to `torch.zeros_like(...)`.

**Comment by GuangtaoLyu** [comment]
thank you for replying. I will try it.



---Original---
From: "Wu ***@***.***&gt;
Date: Sun, Feb 18, 2024 14:28 PM
To: ***@***.***&gt;;
Cc: "Guangtao Lyu ( 吕光涛 ***@***.******@***.***&gt;;
Subject: Re: [PantoMatrix/PantoMatrix] a little bug of test_demo.py  (Issue#109)




 
Hi, thank you for reporting this issue.
 
I think it is because the results has translation thus it is moving, but the camera is being fixed.
 I will try to the fix the camera to look at the center of those vertices.
 
For a temporary workaround, you can try to set the translation to 0 in the following:
 
https://github.com/PantoMatrix/PantoMatrix/blob/2cbbce525cef7ca424473de8b08ee1556a99a014/scripts/EMAGE_2024/utils/other_tools.py#L652
 
https://github.com/PantoMatrix/PantoMatrix/blob/2cbbce525cef7ca424473de8b08ee1556a99a014/scripts/EMAGE_2024/utils/other_tools.py#L665
 
For example, change it to torch.zeros_like(...).
