### ISSUE TITLE
OpenGL Error 

### ISSUE THREAD

**Issue by eehoeskrap** [PantoMatrix/PantoMatrix#117]
Your work is awesome!

However, when I run the demo (scripts/EMAGE_2024/demo.py), the following error occurs. 

- Windows 
- pyglet : 1.5.28
- PyOpenGL : 3.1.0
- pyrender : 0.1.45
- Installed via conda
  - conda create -n emagepy38 python==3.8
  - pip install -r ./scripts/EMAGE_2024/requirements.txt
  - pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'

```
2024-03-20 15:58:44.826 | ERROR    | gradio.utils:wrapper:693 - An error has been caught in function 'wrapper', process 'MainProcess' (41896), thread 'AnyIO worker thread' (35364):
Traceback (most recent call last):

  File "D:\workspace\miniforge3\envs\emage\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           │    │            │       └ {}
           │    │            └ (1,)
           │    └ <function Wrapper.finaliseCall.<locals>.wrapperCall at 0x0000025DC6278430>
           └ <OpenGL.platform.baseplatform.glGenVertexArrays object at 0x0000025D95F9F180>

TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:


...


OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenVertexArrays, check for bool(glGenVertexArrays) before calling

```

Do you know the solution?

**Comment by H-Liu1997** [comment]
@zzhat0706

**Comment by eehoeskrap** [comment]
It works well in a Linux environment.
I'm curious as to why it doesn't work in a Windows environment.

**Comment by zzhat0706** [comment]
Hi, sorry for late reply and thank you for your interest op EMAGE!
![image](https://github.com/PantoMatrix/PantoMatrix/assets/40664546/ca69beee-5901-4f4d-bdaa-41dc003941e6)
We setup our gradio environment, and successfully run on both Windows 10&11. Here is the version of libraries, which are just as same as yours.
Since in the [line 534 of pyrender setting](https://github.com/PantoMatrix/PantoMatrix/blob/71cbd1278ebaca579d253b84a3c9454778d924ad/scripts/EMAGE_2024/utils/other_tools_hf.py#L4), we forced Windows to use EGL of OpenGL from setting pyrender.OffscreenRenderer, so I may temporarily come up with 2 possibilities. 

1. Using of [Windos virtual machine](https://community.khronos.org/t/opengl-error-nullfunctionerror-attempt-to-call-an-undefined-function-glgenvertexarrays-check-for-bool-glgenvertexarrays-before-calling/110241/2)
2.  [Do not connect your using python version with GPU](https://github.com/mmatl/pyrender/issues/176)

**Comment by eehoeskrap** [comment]
Thank you for the detailed explanation!

1. I do not use Windows virtual machines. 😢 
However, I use it by connecting to the Windows environment via ssh from my MacBook.
So, even if I work directly in a Windows environment without ssh, the same error occurs.

2. I also saw that issue. 
I don't know why, but it seems like I can't use the GPU properly in my Windows environment. 
(Model training uses GPU...)
I tested on A100. Can you tell me which GPU architecture you tested on Windows 10/11?

**Comment by zzhat0706** [comment]
1. Yes, when you remotely run GPUs based model on Windows, it cannot access GPUs properly. But even directly is not working. So we can exclude this possibility.
2. [A series(also H series) GPUs cannot accsee WDDM](https://forums.developer.nvidia.com/t/unable-to-get-davinci-running-on-vgpu-on-a100/256094/2), which is the driver for graphics proposing in Windows. I tested on WIndows 10/11 with both of RTX series(2080 and 3060), which have proper WDDM for working with graphics libraries in Windows. I may suggest you to test on RTX series GPUs.

**Comment by eehoeskrap** [comment]
I ran EMAGE well in a Linux environment with RTX 3070.

This doesn't work because it's Linux, but because it's an RTX series, it seems to work. 

I will experiment in the RTX series Windows environment.

Thank you so much!
