### ISSUE TITLE
Some questions about assessment

### ISSUE THREAD

**Issue by cyk990422** [PantoMatrix/PantoMatrix#136]
I noticed that not all of the speaker's test set seemed to be used for evaluation, only 15 audio sequences were used? At the same time, the frame number of some npz files does not seem to correspond to the frame number of wav? For example, the 8_8 sequence pair in the 11th speaker. Thank you very much Dr. Liu for your reply, it is very helpful to me.

**Comment by cyk990422** [comment]
In addition, I discovered during the facial evaluation why rec[1:]-tar[:-1] and tar[1:]-tar[:-1] are used for error calculation in vel_loss instead of rec[1:]-rec[:-1] and tar[1:]-tar[:-1]

**Comment by H-Liu1997** [comment]
Sorry I didn’t get the first question, could you give me more information?

Yes the differences between frame number of wav and npz is due to during
the alignment we dropped several frames in npz

Finally, I feel the loss in face velocity calculation is a bug and the
correct one should be your version.

Thank you for finding this!

**Comment by cyk990422** [comment]
Dear Dr. Liu, thank you very much for your prompt reply, it is very helpful to me.
