### ISSUE TITLE
How to convert the face blendshape weights into the SMPLX expression parameter?

### ISSUE THREAD

**Issue by linjing7** [PantoMatrix/PantoMatrix#21]
Hi, thanks for your excellent work! Could you please tell me how to convert the face blendshape weights into the SMPLX expression parameter?

**Comment by H-Liu1997** [comment]
hi @linjing7 

we are testing the following 3 approaches, and will release the best one:

1.  we have iphone's neutral face mesh for ARkit data (face blendshape weights), and mesh for SMPLX, we first optimize the shape parameters to make it closer to iphone's neutral face, and then optimize the expression parameters for make the expression be closer frame by frame. 
2. we build the 52D blendshape on SMPLX's head mesh manually (for a fixed shape), then we fix this shape parameters and optimize the expression parameters.
3.  we could get ARkit results and SMPLX expression parameters from the same in the wild videos, e.g. TED dataset, then we train a network for mapping ARkit results to SMPLX with these paired training data.  

we will ignore the shape parameters since there is no facial idientity in BEAT dataset. 
Thanks!

**Comment by linjing7** [comment]
Okay, thank you very much.

**Comment by HonglinChu** [comment]
> hi @linjing7
> 
> we are testing the following 3 approaches, and will release the best one:
> 
> 1. we have iphone's neutral face mesh for ARkit data (face blendshape weights), and mesh for SMPLX, we first optimize the shape parameters to make it closer to iphone's neutral face, and then optimize the expression parameters for make the expression be closer frame by frame.
> 2. we build the 52D blendshape on SMPLX's head mesh manually (for a fixed shape), then we fix this shape parameters and optimize the expression parameters.
> 3. we could get ARkit results and SMPLX expression parameters from the same in the wild videos, e.g. TED dataset, then we train a network for mapping ARkit results to SMPLX with these paired training data.
> 
> we will ignore the shape parameters since there is no facial idientity in BEAT dataset. Thanks!

At step2，how to optimize the expression parameters，like this https://github.com/ankarako/flame-fitting？
