### ISSUE TITLE
Name 'decoder_hidden' is not defined error, and some config questions.

### ISSUE THREAD

**Issue by 22TonyFStark** [PantoMatrix/PantoMatrix#26]
Hello Haiyang,
I notice that the model is only trained for 100 epochs, as shown in the config file: [camn_beat_4english_15_141.yaml.](https://github.com/PantoMatrix/BEAT/blob/f4ffee197524076cb705a896b68b4ad237449290/configs/camn_beat_4english_15_141.yaml)
I train a model with more than 200 epochs and meet a NameError: name 'decoder_hidden' is not defined which can be traced to this line:
https://github.com/PantoMatrix/BEAT/blob/f4ffee197524076cb705a896b68b4ad237449290/models/camn.py#L437
It seems that the discriminator could not work, in this case when the epoch number is more than 200, the adversarial loss would be used and the error happens.
Does the "decoder_hidden" matter? Can it be like:
output, _ = self.LSTM(feat)

I wonder if the above config file could train a model with the performance shown in the paper. If not, could you provide one? It would be great if you can also provide some details like how many GPUs should be used and how many hours would be taken for training.

I'm also curious about how the model performs with only text and audio as input(or maybe only using audio). This result could be used more fairly (in my humble opinion) compare to other methods which take only one or two modals(such as A2G, Multi-Context), which I could not find in the paper.

Thank a lot for your time!
Zhongfei Qing

**Comment by H-Liu1997** [comment]
Hi Zhongfei,

1. using config file [camn_beat_4english_15_141.yaml](https://github.com/PantoMatrix/BEAT/blob/f4ffee197524076cb705a896b68b4ad237449290/configs/camn_beat_4english_15_141.yaml) to train a model with `100 epochs` will get the performance shown in the paper, i.e., FGD, Alignment Score, etc. We remove  adv. training finally for a smooth result by just setting `no_adv_training = 200`. 

2. the provided ckpt (in readme.md) is also trained from that config file, using `2V100 GPUS` in `~26h` for `BEAT-16h` data

3. comparison of models with the same input modalities may not the main purpose of BEAT paper, we adopt CaMN for demonstrating the effectiveness of each modal. I may suggest comparing with methods proposed in the same modalites instead of adding one ablation version of CaMN for academic papers. Subjectively, during our experiments the performance with audio + text is similar with Multi-Context as we adopt an advanced wave encoder network, and for the audio only part it performs worse than A2G. 

The detailed logs for 3 are missing, and currently we may not have the plan to reproduce these ablations as we are focusing on release a. benchmark for full-english-data, b. SMPL and FLAME version data, thanks for the understanding!

**Comment by H-Liu1997** [comment]
Thanks for your consideration of the bug in discriminator, and your modification is correct for using adv. training.

**Comment by 22TonyFStark** [comment]
@H-Liu1997 Thanks for your time~

**Comment by pxcai** [comment]
I had the same problem and made the same changes as you did, but the program seems to get stuck. Did you finally solve the problem? Can you give me some advice?
