### ISSUE TITLE
Different reproduced result using English data v0.2.1

### ISSUE THREAD

**Issue by 22TonyFStark** [PantoMatrix/PantoMatrix#28]
Hi Haiyang,
I preprocessed the BEAT-16h from this [link](https://drive.google.com/drive/folders/15NmITxhKEz90z_Hi928A4W8RdDTzfkp5?usp=share_link) and trained it using the default config, I got the corresponding test dataset result as below:
beat align score: 0.795 ↑ 
srgr score: 0.245 ↑
fid score: 76.5 ↓ (this is a kind of large change compared to the paper result, which is about 120)
which is better than the result shown in the paper and the readme.
Here is my reproduced result video, it looks good:
https://user-images.githubusercontent.com/53189297/216563203-4387e2f1-d319-4d8c-aeea-d563db1968a9.mp4
However, I test the model from this [link](https://drive.google.com/file/d/1Q7v_e3K_cgR93a70hlen7KAf2K94NU7j/view?usp=share_link) using my preprocessed data, I got a fid of about 450. So I guess the result shown in the paper is not trained using English data v0.2.1? Or maybe I do something incorrectly？
I notice that some orientations of my preprocessed data are different from the cache data from the [dataset's download link](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL?usp=share_link), as shown below:
![image](https://user-images.githubusercontent.com/53189297/216568119-c4200ede-f082-4612-aa9f-ffbbbd204f3b.png)
I test the cache data using official released weight, and I got a fid about 120, so I guess maybe the cache data is old data or I do something incorrectly.
Which result should I compare to for an academic paper? 
Thanks for your time~
Zhongfei Qing

**Comment by H-Liu1997** [comment]
hi zhongfei, 
yeah this issue is becasue `the cache data is old data`, 

- as listed in [updation](https://github.com/PantoMatrix/BEAT/blob/main/docs/updation.md), one of differences between `v0.2.0` and `v0.2.1` is we change the default T-Pose oritentation, this modifation makes the value of angles (for the same speaker) be different across versions, e.g., `for root rotation Y_v0.2.1 = Y_v0.2.0 - 180`, this difference results in smaller FID. 
- I suggest using  76.5 version, as your method may also be trained on  v0.2.1 data. 

Thanks for your information for the reproduction~!
Haiyang Liu

**Comment by 22TonyFStark** [comment]
@H-Liu1997 Thanks for your reply~ Could you provide a new ae300.bin for FID calculation? Considering the model from this link[[300D AutoEncoder](https://drive.google.com/file/d/1kgUramYf8US2pg1lssJBflDqV3_CJpqH/view?usp=share_link)] may be trained by old data, I think an official pre-trained model(better trained with the whole newly-updated dataset) could be very helpful for a more convincing FID calculation.

**Comment by H-Liu1997** [comment]
hi zhongfei, thanks for your suggestion. personally I could share [ae300 pretrained on full v0.2.1 data](https://drive.google.com/file/d/1qRazyj0_tXbRJSioAf2hblL5jVdkJdXj/view?usp=share_link) here. But please do not consider it as an official weight for FID due to the following concerns:

- subjectively, some authors may already conducted a lot of experiments on their pretrained AE as there is no official one for v0.2.1 data, they may consider re-evaluate their results if there is an new official weight. This re-evaluation is not necessary and may cost a lot of time, authors could keep their AE evalutation weights for a relative comparison for different methods.  
- objectively, an new ae300.bin could only evaluate results from the setting of `joint number=141, training with euler angle`. 
 researchers may adopt different joint numbers and input poes representations, e.g., training with `full body data`, `rot6d`, or `positions`.  they also need to train an AE by theirselves.

overall, you may consider to use this weight for checking reproduction, but it is not necessary to fix this weight in your academic paper. thanks for the understanding!

**Comment by 22TonyFStark** [comment]
@H-Liu1997 Thanks!

**Comment by lmhr** [comment]
> @H-Liu1997 Thanks!

I encountered the same problem as you did at #26. 
How did you manage to solve it at get the score? Do you have any suggestions for me? 
I would appreciate it if you could help me out.

**Comment by lmhr** [comment]
> Hi Haiyang, I preprocessed the BEAT-16h from this [link](https://drive.google.com/drive/folders/15NmITxhKEz90z_Hi928A4W8RdDTzfkp5?usp=share_link) and trained it using the default config, I got the corresponding test dataset result as below: beat align score: 0.795 ↑ srgr score: 0.245 ↑ fid score: 76.5 ↓ (this is a kind of large change compared to the paper result, which is about 120) which is better than the result shown in the paper and the readme. Here is my reproduced result video, it looks good: https://user-images.githubusercontent.com/53189297/216563203-4387e2f1-d319-4d8c-aeea-d563db1968a9.mp4 However, I test the model from this [link](https://drive.google.com/file/d/1Q7v_e3K_cgR93a70hlen7KAf2K94NU7j/view?usp=share_link) using my preprocessed data, I got a fid of about 450. So I guess the result shown in the paper is not trained using English data v0.2.1? Or maybe I do something incorrectly？ I notice that some orientations of my preprocessed data are different from the cache data from the [dataset's download link](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL?usp=share_link), as shown below: ![image](https://user-images.githubusercontent.com/53189297/216568119-c4200ede-f082-4612-aa9f-ffbbbd204f3b.png) I test the cache data using official released weight, and I got a fid about 120, so I guess maybe the cache data is old data or I do something incorrectly. Which result should I compare to for an academic paper? Thanks for your time~ Zhongfei Qing
@22TonyFStark 
I encountered the same problem as you did at https://github.com/PantoMatrix/BEAT/issues/26.
How did you manage to solve it at get the score? Do you have any suggestions for me?
I would appreciate it if you could help me out.

**Comment by xljh0520** [comment]
> Hi Haiyang, I preprocessed the BEAT-16h from this [link](https://drive.google.com/drive/folders/15NmITxhKEz90z_Hi928A4W8RdDTzfkp5?usp=share_link) and trained it using the default config, I got the corresponding test dataset result as below: beat align score: 0.795 ↑ srgr score: 0.245 ↑ fid score: 76.5 ↓ (this is a kind of large change compared to the paper result, which is about 120) which is better than the result shown in the paper and the readme. Here is my reproduced result video, it looks good: https://user-images.githubusercontent.com/53189297/216563203-4387e2f1-d319-4d8c-aeea-d563db1968a9.mp4 However, I test the model from this [link](https://drive.google.com/file/d/1Q7v_e3K_cgR93a70hlen7KAf2K94NU7j/view?usp=share_link) using my preprocessed data, I got a fid of about 450. So I guess the result shown in the paper is not trained using English data v0.2.1? Or maybe I do something incorrectly？ I notice that some orientations of my preprocessed data are different from the cache data from the [dataset's download link](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL?usp=share_link), as shown below: ![image](https://user-images.githubusercontent.com/53189297/216568119-c4200ede-f082-4612-aa9f-ffbbbd204f3b.png) I test the cache data using official released weight, and I got a fid about 120, so I guess maybe the cache data is old data or I do something incorrectly. Which result should I compare to for an academic paper? Thanks for your time~ Zhongfei Qing

Hello,
Thank you for raising this issue. I noticed that you mentioned successfully preprocessing the dataset. I would like to ask you a few questions regarding the dataset preprocessing. Would you be able to help me with these questions?
I noticed that there are no **.npy** files in the provided folder. Could you please let me know how you addressed this issue? Did you convert the **.wav** audio files to the npy file format for storage? If so, what is the shape of the npy file that was stored? 
~~~
def wav2npy(wav_path, npy_path):
    y, sr = librosa.load(wav_path, sr=16000)
    np.save(npy_path)
    return y, sr
~~~
Is it okay if I process it in this way?
Thank you in advance for your time and assistance.

**Comment by MengHao666** [comment]
> uld you be able to help me with these questions?
> I noticed that there are no **.npy** files in the provided folder. Could you please let me kn

you could go through the whole issues so that you could find the solution. There is a solution confirmed by the author.
