### ISSUE TITLE
How can I test my own audios?

### ISSUE THREAD

**Issue by Owen1234560** [PantoMatrix/PantoMatrix#46]
Nice work!
Suppose I have some audio files and corresponding 52 facial expressions, how do I preprocess the files in order to generate motions? Here I only use the pre-trained model provided in the code to make predictions. Can you provide the next detailed steps?

**Comment by H-Liu1997** [comment]
hi,  thanks for your comments for our work,

you may want to generate cache file for inference with your own data. I suggest 

- got textgrid frist as we need text as one input
- write some fake emotion and semantic labels based on the format of  emo and sem files, like all in neutral.
- run preprocessing.ipynb to reduce the fps of audio and facial bsw.
- put the above processed file in the test path
- run test.py

thanks

**Comment by WuweiRE** [comment]
When following the steps above,I find that"align_avg = align/len(self.test_loader)"will go wrong(align will become zero), I guess it's because of the vocab file,but if I tried to rerun the script"bulid vocab",i must train the model again.Can you show me how to run the test script without retraining the model

**Comment by WuweiRE** [comment]
@H-Liu1997
