### ISSUE TITLE
Question about performance of released weights

### ISSUE THREAD

**Issue by lmhr** [PantoMatrix/PantoMatrix#49]
When I use the pre-trained model that you offer, I cannot get the result as you present. Can you help me find out what is wrong?
```
 03-14 13:30:37 | Testing from ckpt ...
 03-14 13:32:52 | align score: 0.788140146902714
 03-14 13:32:52 | srgr score: 0.12233601645691038
 03-14 13:32:52 | l1div score: 2099.2100333580165
 03-14 13:32:52 | fid score: 410.4912763735506
 03-14 13:35:06 | total inference time: 268 s for 6201 s motion
```

**Comment by H-Liu1997** [comment]
Hi, 
could you check #28, may be there is the same issue.
Thanks

**Comment by lmhr** [comment]
Thank you for your reply!
 I have checked the issue, but I don’t think it is related to my problem.
 Could you please send me a runtime log file so that I can troubleshoot it myself? I would be very grateful if you could do that.

**Comment by H-Liu1997** [comment]
hi,

the problem may because the difference between pre-trained model and dataset version

- the pre-trained model is based on dataset v0.1.0, which T-pose is back orientation.
- the current dataset is v0.2.1, which T-pose is front orientation.
- when you test pre-trained model (trained on v0.1.0) on data (v0.2.1), it will have incorrect results.

solution:
1. if you want to test the pre-trained model works well or not, you can consider to run our colab demo
2. or you can follow the steps in readme to reproduce the result by yourself.

thanks

**Comment by lmhr** [comment]
Hi,
Thank you for your reply!
Recently, i have follow the steps in readme to reproduce the result.
But when i use the [code](https://github.com/PantoMatrix/BEAT) and the [data(v0.2.1)](https://drive.google.com/drive/folders/15NmITxhKEz90z_Hi928A4W8RdDTzfkp5) train for 100 epoch even more, i get the result like:
> 03-21 18:09:56 | align score: 0.8263609006114124 
 03-21 18:09:56 | srgr score: 0.24642753691859517
 03-21 18:09:56 | l1div score: 1549.9053151918456
 03-21 18:09:57 | fid score: 402.2426263950729

I always can get a better align  and srgr score. but cannot get the result of fid that shown in the paper. 
I don't realise what's wrong. I have use the different FID calculation which include [ae300 pretrained on full v0.2.1 data](https://drive.google.com/file/d/1qRazyj0_tXbRJSioAf2hblL5jVdkJdXj/view?usp=share_link) and ae300 trained by myself for train.
can you give me some advise?
