### ISSUE TITLE
Audio sequences not align with Facial Blendshapes. 

### ISSUE THREAD

**Issue by euwern** [PantoMatrix/PantoMatrix#73]
I notice that the audio sequences do not align with the facial blendshapes. For instance, the rendered video of facial blendshapes is out of sync with the audio. The audio delay is not consistent throughout the dataset. I wonder what causes the misalignment and what would you propose to fix this issue? 

Please advise, thank you.

**Comment by H-Liu1997** [comment]
hi, thanks for the comments.

the error is due to the performance of iphone's ARkit API, we obtain the audio and facial blendshape weights simultaneously from IPhone 12 Pro. 

In fact for the alignment between audio and facial expressions, as most of the time the iphone works well. we do not plan to fix the raw data, 

instead of that, one possible solution is, you could leverage the output of your network as pesudo label to replace part of groundtruth, to refine your training result. we found that will i) make more accurate alignment ii) make the mouth could close correctly when slience.

**Comment by euwern** [comment]
Thank you for your suggestion. really appreciate it.

**Comment by wubowen416** [comment]
@H-Liu1997 Could you provide which part is not synchornized? Or we have to find out by ourselves?
